= Megasoft’s Calculator

Megasoft’s Calculator perform basic calculations such as add,subtract,multiple,divide and factorial. This Calculator is triggered by CLI and Web APIs.

Integration types are:

* CLI
* Web APIs

Web APIs Intgration document is attached in project only.(Api Document.pdf)

== Installation and Getting Started

Below are the list of prerequisites which you need in order to run this project.

* Ubuntu
* Perl
* Dancer2

Install dancer2 Framework:
[indent=0]
----
	$ sudo apt-get install libdancer2-perl
----

Create dancer2 App:
[indent=0]
----
	$ dancer2 -a restexample::App
----
It will create one project in the same directory with the name of rest example::App.

Clone this project inside your created project.

== Test Case run
[indent=0]
----
	$ perl -Ilib test/testcase.t
----
OutPut:
[indent=0]
----
	[restexample::App:1872] core @2018-07-27 05:05:00> looking for get /factorial/5 in /usr/share/perl5/Dancer2/Core/App.pm l. 1210
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.before_request in (eval 62) l. 1
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.after_request in (eval 62) l. 1
	ok 1 - [GET /] Request successful
	ok 2 - got expected response structure for GET /factorial/5
	[restexample::App:1872] core @2018-07-27 05:05:00> looking for get /factorial in /usr/share/perl5/Dancer2/Core/App.pm l. 1210
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.error.init in (eval 62) l. 1
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.error.before in (eval 62) l. 1
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.error.after in (eval 62) l. 1
	ok 3 - [GET /] Page Not Found
	[restexample::App:1872] core @2018-07-27 05:05:00> looking for post /calculator in /usr/share/perl5/Dancer2/Core/App.pm l. 1210
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.before_request in (eval 62) l. 1
	Use of uninitialized value $number1 in string ne at lib/restexample/App.pm line 15.
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.after_request in (eval 62) l. 1
	ok 4 - [POST /calculator] Addition Request successful
	[restexample::App:1872] core @2018-07-27 05:05:00> looking for post /calculator in /usr/share/perl5/Dancer2/Core/App.pm l. 1210
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.before_request in (eval 62) l. 1
	Use of uninitialized value $number1 in string ne at lib/restexample/App.pm line 15.
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.after_request in (eval 62) l. 1
	ok 5 - [POST /calculator] Subtraction Request successful
	[restexample::App:1872] core @2018-07-27 05:05:00> looking for post /calculator in /usr/share/perl5/Dancer2/Core/App.pm l. 1210
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.before_request in (eval 62) l. 1
	Use of uninitialized value $number1 in string ne at lib/restexample/App.pm line 15.
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.after_request in (eval 62) l. 1
	ok 6 - [POST /calculator] Multiplication Request successful
	[restexample::App:1872] core @2018-07-27 05:05:00> looking for post /calculator in /usr/share/perl5/Dancer2/Core/App.pm l. 1210
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.before_request in (eval 62) l. 1
	Use of uninitialized value $number1 in string ne at lib/restexample/App.pm line 15.
	[restexample::App:1872] core @2018-07-27 05:05:00> Entering hook core.app.after_request in (eval 62) l. 1
	ok 7 - [POST /calculator] Division Request successful
	1..7
----
== CLI Examples

Addition Example
[indent=0]
----
	$ perl Calculator.pl
----
Output:
[indent=0]
----
	Welecome to Megasoft calculator

	1) Add
	2) Subtract
	3) Multiple
	4) Divide
	5) Factorial
	Select Operation : 1
	Enter First number: 10
	Enter Second number: 10
	Result of 10 + 10 = 20

----
Multiplication Example
[indent=0]
----
	$ perl Calculator.pl
----
Output:
[indent=0]
----
	Welecome to Megasoft calculator

	1) Add
	2) Subtract
	3) Multiple
	4) Divide
	5) Factorial
	Select Operation : 3
	Enter First number: 10
	Enter Second number: 10
	Result of 10 * 10 = 100

----
Factorial Example
[indent=0]
----
	$ perl Calculator.pl
----
Output:
[indent=0]
----
	Welecome to Megasoft calculator

	1) Add
	2) Subtract
	3) Multiple
	4) Divide
	5) Factorial
	Select Operation : 5
	Enter First number: 5
	Factorial of 5 = 120
----
Same way you try for subtraction and division.

== Web Examples

I have already attached IDD documnet with project itself. You whould take help of that document for integration.

Strat server:
[indent=0]
----
	$ plackup -r bin/app.psgi
----
Factorial Example
[indent=0]
----
URL: http://localhost:5000/factorial/10
Method: GET
Response Body:
	{
	    "result": 3628800,
	    "factorial_of": "10"
	}
----

Addition Example
[indent=0]
----
URL: http://localhost:5000/calculator
Method: POST
Request Body:
	{
	       "Number1":"20",
	       "Number2":"10",
	       "Operation":"+"
	}
Response Body:
	{
	    "Number2": "10",
	    "Operation": "+",
	    "Number1": "20",
	    "Result": 30
	}
----
Same way you try for multiplication, subtraction and division. 

== Thanks,
